const answers = {
    1: `Mam na imię Artem, mam 17 lat. Urodziłem się na Ukrainie, w mieście Czernihów. W połowie grudnia przeprowadziłem się do Polski.\n\nMam dużą rodzinę. Mam starszą siostrę – ma 18 lat i studiuje w college’u w Poznaniu. Mam też młodszego brata, który ma dopiero 2 lata. Mamy również kota.\n\nNa Ukrainie uczyłem się w liceum matematycznym, które kończę w tym roku ze średnim wynikiem 9. Moimi ulubionymi przedmiotami były angielski i informatyka. Przez około siedem lat dodatkowo uczyłem się angielskiego. Od dwóch lat uczę się w Akademii IT Step na kierunku Programowanie.\n\nJestem osobą towarzyską i łatwo odnajduję się w nowym środowisku. Spokojnie radzę sobie w stresujących sytuacjach. Od ponad 10 lat uprawiam sport – chodziłem na różne sekcje sportowe, a przez ostatnie 4 lata regularnie ćwiczę na siłowni.\n\nW wolnym czasie odpoczywam, słucham muzyki, spaceruję, rysuję albo po prostu zajmuję się swoimi sprawami..`,
    2: `Wybrałem Collegium Da Vinci, ponieważ moim zdaniem to najbardziej kreatywna i ciekawa uczelnia, która oferuje nowoczesne podejście do nauki.\n\nPodoba mi się, że collegium stawia na nowoczesne technologie i daje możliwość nauki w międzynarodowym środowisku.\n\nNa uczelni jest wiele ciekawych klubów, które przyciągają swoją różnorodnością. Planuję zapisać się do jednego z nich, ale jeszcze nie wiem, do którego.\n\nDo Poznania przyjechaliśmy ponieważ w tym mieście studiuje moja siostra, a także mieszka tu wielu naszych znajomych. Dlatego wybraliśmy Poznań.`,
    3: `Wybrałem kierunek E-commerce, ponieważ interesuję się internetem i nowymi technologiami. E-commerce to nowoczesna dziedzina, która zmienia sposób sprzedaży i kontaktu z klientem. Chcę nauczyć się, jak tworzyć sklepy internetowe, jak sprzedawać produkty online i jak prowadzić marketing w internecie.\n\nDzięki E-commerce ludzie mogą robić zakupy szybciej, łatwiej i bez wychodzenia z domu. To dla mnie ciekawe i ważne, ponieważ zakupy online stają się coraz bardziej popularne na całym świecie.`,
    4: `Poznań bardzo mi się podoba\n\nTo zielone miasto — jest tu dużo parków, drzew i miejsc na spacery.\n\nW mieście są ciekawe kawiarnie, muzea, ładne ulice i historyczne centrum.\n\nLubię, że można tu odpocząć i miło spędzić czas z przyjaciółmi.\n\nPoznań to spokojne i nowoczesne miasto, ma dobrą komunikację i wszystko jest blisko.\n\nTutaj studiuje moja siostra i mamy znajomych.\n\nMiasto daje możliwość rozwoju, nauki i odkrywania nowych rzeczy.`,
    5: `Lubię spacerować po parkach w Poznaniu, szczególnie w Cytadeli. Jest tam dużo zieleni, jest ładnie i spokojnie. Lubię też chodzić na Stare Miasto – są tam przytulne uliczki, zabytkowe budynki i miła atmosfera.\n\nCzasami chodzę nad Maltę – to miejsce, gdzie można usiąść, odpocząć i cieszyć się przyrodą. Takie spacery pomagają mi się zrelaksować i oderwać od wszystkiego.`,
    6: `Ostatnia książka, którą przeczytałem, to „Na ostrzu noża” Patricka Nessa.\n\nTo książka science fiction. Akcja dzieje się w dziwnym świecie, gdzie wszyscy ludzie słyszą myśli innych — to się nazywa Szum. Główny bohater to chłopak o imieniu Todd. Mieszka w małym mieście i myśli, że zna całą prawdę o świecie.\nPewnego dnia znajduje miejsce, gdzie nie ma Szumu — jest cisza. Tam spotyka dziewczynę i razem muszą uciekać.\n\nPodczas podróży mają wiele trudnych sytuacji i uczą się, że świat nie jest taki, jak myśleli.\nKsiążka mówi o dorastaniu, wyborach, dobru i złu, zaufaniu i szukaniu prawdy.\nPodobała mi się, bo jest ciekawa, emocjonalna i daje do myślenia.`,
    7: `Ostatni film, który oglądałem, to „Wyspa tajemnic”, nakręcony w 2010 roku <strong><i>(dwa tysiące dziesiątym)</i></strong> przez reżysera Martina Scorsese. Główną rolę zagrał Leonardo DiCaprio.\n\nTo psychologiczny thriller. Akcja dzieje się w 1954 roku <strong><i>(tysiąc dziewięćset pięćdziesiątym czwartym)</i></strong>. Główny bohater Teddy Daniels — przyjeżdża z partnerem na wyspę, gdzie jest zamknięty szpital psychiatryczny dla niebezpiecznych przestępców.\nProwadzą śledztwo w sprawie zniknięcia pacjentki.\n\nPodczas śledztwa dzieją się dziwne rzeczy. Personel nie chce pomagać, dokumenty są ukrywane, a Teddy zaczyna mieć dziwne sny i halucynacje związane z jego przeszłością. Przypomina sobie żonę, która zginęła, i wojnę, w której walczył.\n\nPodobał mi się ten film, bo jest bardzo głęboki, z ciekawą fabułą i dobrą grą aktorską. Daje do myślenia o tym, czym jest rzeczywistość i jak łatwo ją stracić.`,
    8: `Zainteresowałem się programowaniem już kilka lat temu. Na początku było to tylko hobby, ale z czasem bardzo mnie to wciągnęło. Teraz uczę się programowania w akademii IT i rozwijam się też samodzielnie.\n\nZnam podstawy C++, C#, JavaScript, dobrze radzę sobie z HTML i CSS. Mam też wysoki poziom angielskiego, co bardzo pomaga mi w nauce programowania i w codziennym życiu.`,
    9: `Wybrałem naukę po polsku, bo tak będzie mi łatwiej. Znam angielski, ale ten język bardzo różni się od mojego. W czasie nauki mogą być trudności. Polski jest podobny do mojego języka, dlatego lepiej rozumiem i łatwiej mi się uczyć. Chcę też dalej rozwijać polski i używać go w przyszłości.`,
    10: `Jeszcze dużo o tym nie myślałem. Na początku chcę dobrze się uczyć i zdobyć zawód. Ale jeśli będzie możliwość pracy w czasie studiów, to chętnie spróbuję. Myślę, że to może być ciekawy i przydatny doświadczenie.<hr>\n<strong>Jako kto chciałbyś dorabiać? (Jaką pracę chciałbyś wykonywać?)</strong>\nNie wiem jeszcze, jaka to może być praca. Jeśli będzie taka opcja, wybiorę coś z dostępnych ofert. Każda praca da mi nowe doświadczenie i umiejętności – to na pewno się przyda.`,
    11: `W moim życiu ważne są takie rzeczy jak: czytanie, granie w gry, sport, programowanie, astronomia i oglądanie anime.\n\nNajwiększą moją pasją jest oglądanie anime i czytanie książek. Kiedyś robiłem to codziennie, bo przenosiło mnie to do innego, ciekawego świata. Bardzo lubiłem oglądać filmy i anime z kolegami, a także czytać książki fantastyczne i przygodowe. Teraz robię to rzadziej, bo mam mniej wolnego czasu.\n\nCzas od czasu gram w gry komputerowe, zazwyczaj z kolegami. Lubię też sport – uprawiam go prawie codziennie.\n\nInteresuję się również astronomią, bo to bardzo ciekawa nauka o wszechświecie.\n\nPodsumowując, hobby to bardzo ważna część mojego życia. Pomaga mi odpocząć, rozwijać się i mieć czas tylko dla siebie.`, 
    12: `Nie miałem wcześniej okazji być w Polsce. Przyjechałem tutaj po raz pierwszy w grudniu zeszłego roku. Wszystko było dla mnie nowe, ale szybko się przyzwyczaiłem i teraz czuję się tu dobrze.`,
    13: `Uczę się języka polskiego od około dwóch lat. Na początku uczyłem się przez półtora roku, później miałem przerwę. Od września tego roku znów kontynuuję naukę.\n\nPlanuję dalej rozwijać swój polski, ucząc się regularnie, rozmawiając z ludźmi i używając języka w pracy oraz w codziennym życiu.`,
    14: `Chciałbym odwiedzić różne miejsca w Polsce. Na pewno Warszawę, bo to stolica i jest tam dużo ciekawych miejsc – Stare Miasto, Pałac Kultury i Nauki, muzea.\n\nChciałbym też zobaczyć Kraków – piękne miasto z historią. Są tam Wawel, Rynek i Kościół Mariacki.\n\nInteresuje mnie też Gdańsk nad morzem – można tam odpocząć i spacerować. Chciałbym też pojechać w góry – do Zakopanego i w Tatry.\n\nLubię zamki, więc chciałbym zobaczyć Zamek Królewski w Warszawie i Malbork.\n\nW Polsce jest wiele ciekawych miejsc i chciałbym je poznać.`,
    15: `Chciałbym odwiedzić Japonię, ponieważ bardzo interesuje mnie ta kultura. Podziwiam, jak szybko kraj się rozwinął po wojnie. Lubię japońską kuchnię, tradycje i nowoczesne technologie. Marzę o tym, żeby zobaczyć Tokio i spokojne świątynie w Kioto.\n\nChciałbym też pojechać do Włoch, żeby zobaczyć starożytny Koloseum i spróbować prawdziwej włoskiej pizzy.\n\nInnym krajem, który chciałbym odwiedzić, są Niemcy — chciałbym zobaczyć Katedrę w Kolonii i poznać jego historię.`,
    16: `Zdecydowałem się studiować za granicą, bo to wydaje mi się bardziej przyszłościowe. Studia w innym kraju to nie tylko dobra edukacja, ale też szansa poznać nową kulturę, poprawić języki obce i nauczyć się samodzielności. Za granicą jest więcej możliwości rozwoju osobistego i zawodowego, a także większe szanse na międzynarodową karierę. Uważam, że takie studia mogą otworzyć przede mną więcej drzwi w przyszłości.`,
    17: `Po studiach chciałbym znaleźć pracę w dobrej firmie, żeby zdobyć doświadczenie i wykorzystać wiedzę w praktyce. Może w przyszłości otworzę własny sklep albo firmę, ale jeszcze o tym nie myślałem. Wszystko zależy od możliwości, które będę miał.`,
    18: `Na obrazku widzimy rodzinę w lesie – ojca i dwie córki.\nOjciec ma na sobie ciemnoniebieską kurtkę, dżinsowe spodnie, buty, czapkę i plecak.\nMłodsza córka stoi w środku. Jest ubrana w różową kurtkę, czapkę, szalik, ciemne spodnie i buty.\nMłodsza córka stoi w środku. Jest ubrana w różową kurtkę, czapkę, szalik, ciemne spodnie i buty.\nStarsza córka jest po prawej stronie. Ma jasną kurtkę, czapkę, spodnie i buty. Trzyma pluszowego misia.\nWygląda na to, że spacerują i odpoczywają od hałasu miasta w weekend.\nNa ścieżce i wokół widać żółte liście, więc pewnie jest jesień.
    <hr><img src="img/ludzi_w_lesie.jpg" alt="Poznań" style="display: block; margin: 20px auto; max-width: 50%; height: auto; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.2);">`
};
  
  document.getElementById("question_select").addEventListener("change", function () {
    const val = this.value;
    const container = document.getElementById("answer_container");
    container.innerHTML = answers[val] || "";
  });

  